# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - id: tagpr
        uses: Songmu/tagpr@v1
      - name: Checkout released
        uses: actions/checkout@v4
        if: ${{ steps.tagpr.outputs.tag != '' }}
        with:
          ref: ${{ steps.tagpr.outputs.tag }}
      - name: Set up Go
        uses: actions/setup-go@v4
        if: ${{ steps.tagpr.outputs.tag != '' }}
        with:
            go-version: "1.21"
      - name: Run Go Releaser
        uses: goreleaser/goreleaser-action@v5
        if: ${{ steps.tagpr.outputs.tag != '' }}
        with:
          version: latest
          args: release
      - name: Release Image
        if: ${{ steps.tagpr.outputs.tag != '' }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker build --tag ghcr.io/mashiike/ecs-task-self-terminator:${{ steps.tagpr.outputs.tag }} .
          docker push ghcr.io/mashiike/ecs-task-self-terminator:${{ steps.tagpr.outputs.tag }}
